<?php

namespace Database\Seeders;

use App\Models\Package;
use Illuminate\Database\Seeder;

class AllPackagesSeeder extends Seeder
{
    /**
     * Seeds all 14 current packages - the original 6 plus the 8 added in the
     * "New package concepts" session - with their exact live production
     * content: highlights, itinerary, inclusions/exclusions, quick facts
     * (trip_grade, group size, best season, meals/accommodation notes), and
     * final image/gallery paths.
     *
     * Unlike PackageSeeder (which migrates the original static
     * resources/data/packages.php content and copies images out of
     * public/images/ into the "public" storage disk as a one-time
     * migration), this seeder writes directly against the "public" disk
     * paths the images already live at - nothing here needs copying, since
     * every image referenced below is already deployed to
     * storage/app/public/packages/ (and storage/app/public/regions/ for the
     * few gallery slots that intentionally reuse a region photo).
     *
     * Safe to re-run: uses updateOrCreate keyed on slug, same as
     * PackageSeeder. Registered in DatabaseSeeder to run after
     * PackageSeeder, so this is the authoritative final state for all 14
     * packages regardless of what PackageSeeder leaves behind.
     */
    public function run(): void
    {
        $packages = [
            [
                'title' => 'Pokhara',
                'slug' => 'pokhara',
                'category' => 'Trekking',
                'duration' => '6 Days',
                'description' => 'The ultimate pilgrimage for mountain lovers through the Annapurna foothills and turquoise lakes.',
                'price' => '1650.00',
                'badge' => 'featured',
                'image' => 'packages/pokhara.webp',
                'gallery' => [
                    'packages/pokhara.webp',
                    'regions/pokhara.png',
                    'packages/gallery/pokhara-3.webp',
                    'packages/gallery/pokhara-4.webp',
                ],
                'highlights' => [
                    'Sunrise views of the Annapurna range from Sarangkot',
                    'Boating on the turquoise waters of Phewa Lake',
                    'Visit to the World Peace Pagoda',
                    'Guided walk through traditional Gurung villages',
                ],
                'itinerary' => [
                    [
                        'day' => 1,
                        'title' => 'Arrival in Pokhara',
                        'description' => 'Transfer from Kathmandu and settle in at the lakeside. Evening at leisure around Phewa Lake.',
                    ],
                    [
                        'day' => 2,
                        'title' => 'Sarangkot Sunrise Trek',
                        'description' => 'Early morning drive and short hike to Sarangkot for panoramic sunrise views over the Annapurna range.',
                    ],
                    [
                        'day' => 3,
                        'title' => 'Annapurna Foothills',
                        'description' => 'Trek through terraced fields and Gurung villages toward the base of the foothills.',
                    ],
                    [
                        'day' => 4,
                        'title' => 'Village Immersion',
                        'description' => 'Full day exploring local culture, home-cooked meals, and traditional crafts.',
                    ],
                    [
                        'day' => 5,
                        'title' => 'Phewa Lake & World Peace Pagoda',
                        'description' => 'Boat across Phewa Lake and hike up to the World Peace Pagoda for valley views.',
                    ],
                    [
                        'day' => 6,
                        'title' => 'Departure',
                        'description' => 'Free morning at leisure before transfer back to Kathmandu.',
                    ],
                ],
                'inclusions' => [
                    'Airport and lakeside transfers',
                    'Licensed English-speaking guide',
                    'Accommodation (5 nights)',
                    'Daily breakfast',
                    'All permits and entrance fees',
                ],
                'exclusions' => [
                    'International flights',
                    'Nepal visa fees',
                    'Travel insurance',
                    'Lunch and dinner',
                    'Personal expenses and tips',
                ],
                'is_active' => true,
                'trip_grade' => null,
                'group_size_min' => null,
                'group_size_max' => null,
                'best_season' => null,
                'meals_note' => null,
                'accommodation_note' => null,
            ],
            [
                'title' => 'Chitwan Safari',
                'slug' => 'chitwan-safari',
                'category' => 'Wildlife',
                'duration' => '3 Days',
                'description' => 'Explore the sub-tropical jungles and encounter the endangered one-horned rhino.',
                'price' => '950.00',
                'badge' => 'best_price',
                'image' => 'packages/chitwan-safari.webp',
                'gallery' => [
                    'packages/chitwan-safari.webp',
                    'packages/gallery/chitwan-safari-2.webp',
                    'packages/gallery/chitwan-safari-3.webp',
                ],
                'highlights' => [
                    'Jungle safari in Chitwan National Park',
                    'Chance encounters with one-horned rhinos and gharial crocodiles',
                    'Canoe ride along the Rapti River',
                    'Traditional Tharu cultural performance',
                ],
                'itinerary' => [
                    [
                        'day' => 1,
                        'title' => 'Arrival & Canoe Ride',
                        'description' => 'Transfer to Chitwan, afternoon canoe ride along the Rapti River, and village walk.',
                    ],
                    [
                        'day' => 2,
                        'title' => 'Jungle Safari',
                        'description' => 'Full-day jeep safari through the national park in search of rhinos, deer, and birdlife.',
                    ],
                    [
                        'day' => 3,
                        'title' => 'Departure',
                        'description' => 'Morning nature walk before transfer back to Kathmandu or Pokhara.',
                    ],
                ],
                'inclusions' => [
                    'Park entrance fees and permits',
                    'Jeep safari and canoe ride',
                    'Accommodation (2 nights)',
                    'All meals during the safari',
                    'Naturalist guide',
                ],
                'exclusions' => [
                    'International flights',
                    'Nepal visa fees',
                    'Travel insurance',
                    'Alcoholic beverages',
                    'Personal expenses and tips',
                ],
                'is_active' => true,
                'trip_grade' => null,
                'group_size_min' => null,
                'group_size_max' => null,
                'best_season' => null,
                'meals_note' => null,
                'accommodation_note' => null,
            ],
            [
                'title' => 'Mustang',
                'slug' => 'mustang',
                'category' => 'Cultural',
                'duration' => '8 Days',
                'description' => 'Discover the forbidden kingdom of Lo, a pocket of Tibetan culture hidden beyond the Himalaya.',
                'price' => '1850.00',
                'badge' => 'sold_out',
                'image' => 'packages/mustang.webp',
                'gallery' => [
                    'packages/mustang.webp',
                    'regions/mustang.png',
                    'packages/gallery/mustang-3.webp',
                ],
                'highlights' => [
                    'Walled city of Lo Manthang, the ancient capital',
                    'Centuries-old monasteries and cave dwellings',
                    'Dramatic desert-like Himalayan rain-shadow landscape',
                    'Encounters with traditional Tibetan Buddhist culture',
                ],
                'itinerary' => [
                    [
                        'day' => 1,
                        'title' => 'Fly to Jomsom',
                        'description' => 'Scenic mountain flight to Jomsom, trek to Kagbeni at the edge of Upper Mustang.',
                    ],
                    [
                        'day' => 2,
                        'title' => 'Kagbeni to Chele',
                        'description' => 'Enter the restricted region and trek through arid canyons to Chele.',
                    ],
                    [
                        'day' => 3,
                        'title' => 'Chele to Syangboche',
                        'description' => 'Cross high passes with views of the Nilgiri and Damodar ranges.',
                    ],
                    [
                        'day' => 4,
                        'title' => 'Syangboche to Ghami',
                        'description' => 'Pass ancient chortens and red cliffs en route to the village of Ghami.',
                    ],
                    [
                        'day' => 5,
                        'title' => 'Ghami to Charang',
                        'description' => 'Visit the red monastery and dzong (fort) overlooking the valley.',
                    ],
                    [
                        'day' => 6,
                        'title' => 'Charang to Lo Manthang',
                        'description' => 'Arrive at the walled capital of the former Kingdom of Lo.',
                    ],
                    [
                        'day' => 7,
                        'title' => 'Explore Lo Manthang',
                        'description' => 'Full day visiting royal palace, monasteries, and surrounding caves.',
                    ],
                    [
                        'day' => 8,
                        'title' => 'Return & Departure',
                        'description' => 'Retrace the route back to Jomsom for the return flight.',
                    ],
                ],
                'inclusions' => [
                    'Restricted area permit (Upper Mustang)',
                    'Domestic flights (Pokhara–Jomsom return)',
                    'Licensed guide and porter support',
                    'Teahouse accommodation',
                    'All meals during the trek',
                ],
                'exclusions' => [
                    'International flights',
                    'Nepal visa fees',
                    'Travel insurance',
                    'Hot showers and Wi-Fi at teahouses',
                    'Personal expenses and tips',
                ],
                'is_active' => true,
                'trip_grade' => null,
                'group_size_min' => null,
                'group_size_max' => null,
                'best_season' => null,
                'meals_note' => null,
                'accommodation_note' => null,
            ],
            [
                'title' => 'Everest Base Camp',
                'slug' => 'everest-base-camp',
                'category' => 'Trekking',
                'duration' => '14 Days',
                'description' => 'Follow the classic Khumbu trail past Sherpa villages to the foot of the world\'s highest peak.',
                'price' => '2450.00',
                'badge' => 'featured',
                'image' => 'packages/everest-base-camp.webp',
                'gallery' => [
                    'packages/everest-base-camp.webp',
                    'packages/gallery/everest-base-camp-2.webp',
                    'packages/gallery/everest-base-camp-3.webp',
                ],
                'highlights' => [
                    'Standing at Everest Base Camp, 5,364m',
                    'Sunrise over the Khumbu range from Kala Patthar',
                    'Sherpa villages of Namche Bazaar and Tengboche',
                    'Sagarmatha National Park, a UNESCO World Heritage Site',
                ],
                'itinerary' => [
                    [
                        'day' => 1,
                        'title' => 'Fly to Lukla, Trek to Phakding',
                        'description' => 'Scenic flight into Lukla followed by a gentle trek to Phakding.',
                    ],
                    [
                        'day' => 2,
                        'title' => 'Namche Bazaar',
                        'description' => 'Climb to the Sherpa capital of the Khumbu, with views of Everest along the way.',
                    ],
                    [
                        'day' => 3,
                        'title' => 'Acclimatization Day',
                        'description' => 'Rest day in Namche with an optional hike to the Everest View Hotel.',
                    ],
                    [
                        'day' => 4,
                        'title' => 'Tengboche',
                        'description' => 'Trek to Tengboche Monastery, the spiritual heart of the Khumbu.',
                    ],
                    [
                        'day' => 5,
                        'title' => 'Dingboche',
                        'description' => 'Continue up the valley through rhododendron forest into the alpine zone.',
                    ],
                    [
                        'day' => 6,
                        'title' => 'Acclimatization Day',
                        'description' => 'Rest day in Dingboche with an optional hike to Nangkartshang Peak.',
                    ],
                    [
                        'day' => 7,
                        'title' => 'Lobuche',
                        'description' => 'Trek past the Khumbu Glacier memorials to Lobuche.',
                    ],
                    [
                        'day' => 8,
                        'title' => 'Everest Base Camp',
                        'description' => 'Trek via Gorak Shep to Everest Base Camp itself, then back to Gorak Shep.',
                    ],
                    [
                        'day' => 9,
                        'title' => 'Kala Patthar & Pheriche',
                        'description' => 'Pre-dawn climb to Kala Patthar for sunrise views of Everest, then descend to Pheriche.',
                    ],
                    [
                        'day' => 10,
                        'title' => 'Namche Bazaar',
                        'description' => 'Long descent back through Tengboche to Namche Bazaar.',
                    ],
                    [
                        'day' => 11,
                        'title' => 'Lukla',
                        'description' => 'Final descent back to Lukla.',
                    ],
                    [
                        'day' => 12,
                        'title' => 'Fly to Kathmandu',
                        'description' => 'Morning flight back to Kathmandu with the rest of the day at leisure.',
                    ],
                    [
                        'day' => 13,
                        'title' => 'Contingency Day',
                        'description' => 'Buffer day reserved for weather-related flight delays.',
                    ],
                    [
                        'day' => 14,
                        'title' => 'Departure',
                        'description' => 'Transfer to the airport for onward travel.',
                    ],
                ],
                'inclusions' => [
                    'Sagarmatha National Park permit and TIMS card',
                    'Domestic flights (Kathmandu–Lukla return)',
                    'Licensed guide and porter support',
                    'Teahouse accommodation',
                    'All meals during the trek',
                ],
                'exclusions' => [
                    'International flights',
                    'Nepal visa fees',
                    'Travel insurance',
                    'Hot showers and battery charging at teahouses',
                    'Personal expenses and tips',
                ],
                'is_active' => true,
                'trip_grade' => null,
                'group_size_min' => null,
                'group_size_max' => null,
                'best_season' => null,
                'meals_note' => null,
                'accommodation_note' => null,
            ],
            [
                'title' => 'Annapurna Circuit',
                'slug' => 'annapurna-circuit',
                'category' => 'Trekking',
                'duration' => '12 Days',
                'description' => 'Circle the Annapurna massif through terraced villages, pine forests, and high mountain passes.',
                'price' => '2100.00',
                'badge' => null,
                'image' => 'packages/annapurna-circuit.webp',
                'gallery' => [
                    'packages/annapurna-circuit.webp',
                    'packages/gallery/annapurna-circuit-2.webp',
                    'packages/gallery/annapurna-circuit-3.webp',
                ],
                'highlights' => [
                    'Crossing the Thorong La Pass at 5,416m',
                    'Diverse landscapes from subtropical valleys to high desert',
                    'Natural hot springs at Tatopani',
                    'Views of Annapurna, Dhaulagiri, and Manaslu',
                ],
                'itinerary' => [
                    [
                        'day' => 1,
                        'title' => 'Drive to Besisahar',
                        'description' => 'Drive from Kathmandu to the trailhead at Besisahar.',
                    ],
                    [
                        'day' => 2,
                        'title' => 'Chame',
                        'description' => 'Trek through forested valleys to the district headquarters of Chame.',
                    ],
                    [
                        'day' => 3,
                        'title' => 'Pisang',
                        'description' => 'Continue upriver with views of the Annapurna II and IV.',
                    ],
                    [
                        'day' => 4,
                        'title' => 'Manang',
                        'description' => 'Trek to Manang, the last major village before the pass.',
                    ],
                    [
                        'day' => 5,
                        'title' => 'Acclimatization Day',
                        'description' => 'Rest day in Manang with an optional hike for acclimatization.',
                    ],
                    [
                        'day' => 6,
                        'title' => 'Yak Kharka',
                        'description' => 'Short trek higher up the valley to aid acclimatization.',
                    ],
                    [
                        'day' => 7,
                        'title' => 'Thorong Phedi',
                        'description' => 'Trek to the base camp for the Thorong La Pass crossing.',
                    ],
                    [
                        'day' => 8,
                        'title' => 'Thorong La Pass to Muktinath',
                        'description' => 'Early start to cross the 5,416m pass, descending to the pilgrimage site of Muktinath.',
                    ],
                    [
                        'day' => 9,
                        'title' => 'Marpha',
                        'description' => 'Descend through the Kali Gandaki valley to the apple-growing village of Marpha.',
                    ],
                    [
                        'day' => 10,
                        'title' => 'Tatopani',
                        'description' => 'Continue down valley to relax in the natural hot springs at Tatopani.',
                    ],
                    [
                        'day' => 11,
                        'title' => 'Ghorepani',
                        'description' => 'Climb toward Ghorepani through rhododendron forest.',
                    ],
                    [
                        'day' => 12,
                        'title' => 'Poon Hill & Pokhara',
                        'description' => 'Sunrise at Poon Hill before descending to the trailhead and driving to Pokhara.',
                    ],
                ],
                'inclusions' => [
                    'Annapurna Conservation Area permit and TIMS card',
                    'Licensed guide and porter support',
                    'Teahouse accommodation',
                    'All meals during the trek',
                    'Ground transport to and from the trailhead',
                ],
                'exclusions' => [
                    'International flights',
                    'Nepal visa fees',
                    'Travel insurance',
                    'Hot showers and Wi-Fi at teahouses',
                    'Personal expenses and tips',
                ],
                'is_active' => true,
                'trip_grade' => null,
                'group_size_min' => null,
                'group_size_max' => null,
                'best_season' => null,
                'meals_note' => null,
                'accommodation_note' => null,
            ],
            [
                'title' => 'Langtang Valley',
                'slug' => 'langtang-valley',
                'category' => 'Trekking',
                'duration' => '7 Days',
                'description' => 'A quieter Himalayan trail through rhododendron forests and glacial valleys near Kathmandu.',
                'price' => '1450.00',
                'badge' => 'best_price',
                'image' => 'packages/langtang-valley.webp',
                'gallery' => [
                    'packages/langtang-valley.webp',
                    'packages/gallery/langtang-valley-2.webp',
                    'packages/gallery/langtang-valley-3.webp',
                ],
                'highlights' => [
                    'Langtang Lirung glacier views',
                    'Kyanjin Gompa monastery and cheese factory',
                    'Rhododendron and bamboo forests',
                    'Tamang and Sherpa mountain villages',
                ],
                'itinerary' => [
                    [
                        'day' => 1,
                        'title' => 'Drive to Syabrubesi',
                        'description' => 'Scenic drive from Kathmandu to the trailhead village of Syabrubesi.',
                    ],
                    [
                        'day' => 2,
                        'title' => 'Lama Hotel',
                        'description' => 'Trek through forest along the Langtang River to Lama Hotel.',
                    ],
                    [
                        'day' => 3,
                        'title' => 'Langtang Village',
                        'description' => 'Continue up the valley to Langtang Village, rebuilt after the 2015 earthquake.',
                    ],
                    [
                        'day' => 4,
                        'title' => 'Kyanjin Gompa',
                        'description' => 'Short trek to Kyanjin Gompa with time to visit the monastery and cheese factory.',
                    ],
                    [
                        'day' => 5,
                        'title' => 'Acclimatization Day',
                        'description' => 'Optional hike to Kyanjin Ri or Tserko Ri for panoramic glacier views.',
                    ],
                    [
                        'day' => 6,
                        'title' => 'Lama Hotel',
                        'description' => 'Descend back through the valley to Lama Hotel.',
                    ],
                    [
                        'day' => 7,
                        'title' => 'Syabrubesi & Departure',
                        'description' => 'Final descent to Syabrubesi and drive back to Kathmandu.',
                    ],
                ],
                'inclusions' => [
                    'Langtang National Park permit and TIMS card',
                    'Licensed guide and porter support',
                    'Teahouse accommodation',
                    'All meals during the trek',
                    'Ground transport to and from the trailhead',
                ],
                'exclusions' => [
                    'International flights',
                    'Nepal visa fees',
                    'Travel insurance',
                    'Hot showers and Wi-Fi at teahouses',
                    'Personal expenses and tips',
                ],
                'is_active' => true,
                'trip_grade' => null,
                'group_size_min' => null,
                'group_size_max' => null,
                'best_season' => null,
                'meals_note' => null,
                'accommodation_note' => null,
            ],
            [
                'title' => 'Kathmandu Valley Day Tour',
                'slug' => 'kathmandu-valley-day-tour',
                'category' => 'Cultural',
                'duration' => '1 Day',
                'description' => 'A full day through Kathmandu Valley\'s five most iconic heritage sites, from ancient palace squares to sacred stupas and riverside temples.',
                'price' => '65.00',
                'badge' => null,
                'image' => 'packages/kathmandu-valley-day-tour.webp',
                'gallery' => [
                    'packages/kathmandu-valley-day-tour.webp',
                    'packages/gallery/kathmandu-valley-day-tour-2.webp',
                    'packages/gallery/kathmandu-valley-day-tour-3.webp',
                    'packages/gallery/kathmandu-valley-day-tour-4.webp',
                    'packages/gallery/kathmandu-valley-day-tour-5.webp',
                ],
                'highlights' => [
                    'Kathmandu Durbar Square\'s palace complex and wood-carved temples',
                    'Patan Durbar Square, the valley\'s best-preserved Newari courtyard',
                    'Swayambhunath\'s hilltop stupa and panoramic valley views',
                    'Boudhanath, one of the largest stupas in the world',
                    'Riverside cremation ghats and sadhu culture at Pashupatinath',
                    'A private guide fluent in the valley\'s Hindu and Buddhist history',
                ],
                'itinerary' => [
                    [
                        'day' => 1,
                        'title' => 'Kathmandu Valley Heritage Circuit',
                        'description' => 'Begin at Kathmandu Durbar Square\'s palace complex, then continue to Swayambhunath\'s hilltop stupa for valley views. After lunch, visit the ancient stupa at Boudhanath and the riverside temples of Pashupatinath, finishing the day at Patan Durbar Square.',
                    ],
                ],
                'inclusions' => [
                    'Private vehicle and driver for the full day',
                    'Licensed English-speaking guide',
                    'All monument entrance fees',
                    'Hotel pickup and drop-off in Kathmandu',
                ],
                'exclusions' => [
                    'International flights',
                    'Nepal visa fees',
                    'Lunch and personal expenses',
                    'Travel insurance',
                    'Gratuities for guide and driver',
                ],
                'is_active' => true,
                'trip_grade' => 'Easy',
                'group_size_min' => 1,
                'group_size_max' => 12,
                'best_season' => 'Year-round (clearest Oct-Apr)',
                'meals_note' => 'Lunch available at your own cost at a local restaurant',
                'accommodation_note' => 'Day tour - no overnight stay required',
            ],
            [
                'title' => 'Chandragiri Hills Day Tour',
                'slug' => 'chandragiri-hills-day-tour',
                'category' => 'Sightseeing',
                'duration' => 'Half-Day',
                'description' => 'A cable car ride above Kathmandu Valley to a Himalayan viewpoint — low effort, high reward, and ideal for travelers who want mountain views without a trek.',
                'price' => '55.00',
                'badge' => null,
                'image' => 'packages/chandragiri-hills-day-tour.webp',
                'gallery' => [
                    'packages/chandragiri-hills-day-tour.webp',
                    'packages/gallery/chandragiri-hills-day-tour-2.webp',
                    'packages/gallery/chandragiri-hills-day-tour-3.webp',
                ],
                'highlights' => [
                    'Scenic cable car ride to 2,551m above the valley floor',
                    'Panoramic views of the Kathmandu Valley from the summit',
                    'Distant sightings of Annapurna, Manaslu, and Langtang on clear days',
                    'Bhaleshwor Mahadev, a hilltop Shiva temple',
                    'Gentle summit trails suitable for most fitness levels',
                    'A relaxed, low-logistics escape from the city',
                ],
                'itinerary' => [
                    [
                        'day' => 1,
                        'title' => 'Chandragiri Hills Cable Car & Summit',
                        'description' => 'Drive from Kathmandu to the Chandragiri cable car station, then ride to the summit for panoramic Himalayan views. Explore the hilltop temple and viewpoints before returning by cable car and driving back to the city.',
                    ],
                ],
                'inclusions' => [
                    'Private vehicle from Kathmandu to the cable car station and back',
                    'Return cable car ticket',
                    'Licensed guide',
                    'Hotel pickup and drop-off',
                ],
                'exclusions' => [
                    'Meals and drinks at the summit',
                    'Personal expenses and tips',
                    'Travel insurance',
                ],
                'is_active' => true,
                'trip_grade' => 'Easy',
                'group_size_min' => 1,
                'group_size_max' => 15,
                'best_season' => 'Sep-May (clearest mountain views)',
                'meals_note' => 'Not included - cafes available at the summit',
                'accommodation_note' => 'Half-day tour - no overnight stay required',
            ],
            [
                'title' => 'Pokhara Valley Getaway',
                'slug' => 'pokhara-valley-getaway',
                'category' => 'Leisure',
                'duration' => '2 Days',
                'description' => 'A relaxed two-day escape to Pokhara\'s lakeside — sunrise mountain views, a floating pagoda, and a jungle waterfall, without a single day of trekking.',
                'price' => '320.00',
                'badge' => null,
                'image' => 'packages/pokhara.webp',
                'gallery' => [
                    'packages/pokhara.webp',
                    'packages/gallery/pokhara-3.webp',
                    'packages/gallery/pokhara-valley-getaway-3.webp',
                    'packages/gallery/pokhara-valley-getaway-4.webp',
                ],
                'highlights' => [
                    'Sunrise over the Annapurna range from Sarangkot',
                    'Boating across Phewa Lake to the World Peace Pagoda',
                    'Davis Falls\' underground gorge and waterfall',
                    'A full free evening to explore Pokhara\'s lakeside strip',
                    'Relaxed pace — no trekking or high-altitude walking required',
                    'Optional add-on adventure activities available (see Pokhara Adventure Add-ons)',
                ],
                'itinerary' => [
                    [
                        'day' => 1,
                        'title' => 'Arrival & Phewa Lake',
                        'description' => 'Arrive in Pokhara and settle in at the lakeside. Afternoon boat ride across Phewa Lake to the World Peace Pagoda, followed by free time along the lakeside strip.',
                    ],
                    [
                        'day' => 2,
                        'title' => 'Sarangkot Sunrise & Davis Falls',
                        'description' => 'Early drive to Sarangkot for sunrise over the Annapurna range, then visit Davis Falls and the Gupteshwor Cave before departure.',
                    ],
                ],
                'inclusions' => [
                    'Airport/bus park transfers in Pokhara',
                    'Accommodation (1 night, lakeside)',
                    'Daily breakfast',
                    'Phewa Lake boat ride and World Peace Pagoda entry',
                    'Sarangkot sunrise transfer',
                    'Davis Falls and Gupteshwor Cave entrance fees',
                ],
                'exclusions' => [
                    'Transport to/from Kathmandu',
                    'Lunch and dinner',
                    'Personal expenses and tips',
                    'Travel insurance',
                ],
                'is_active' => true,
                'trip_grade' => 'Easy',
                'group_size_min' => 1,
                'group_size_max' => 10,
                'best_season' => 'Oct-Apr',
                'meals_note' => 'Daily breakfast included',
                'accommodation_note' => 'Lakeside hotel (1 night)',
            ],
            [
                'title' => 'Chitwan Wildlife Safari',
                'slug' => 'chitwan-wildlife-safari',
                'category' => 'Wildlife',
                'duration' => '2 Days',
                'description' => 'A quick, budget-friendly introduction to Chitwan National Park — jungle safari, river canoeing, and Tharu culture packed into a tight two-day trip.',
                'price' => '650.00',
                'badge' => null,
                'image' => 'packages/chitwan-wildlife-safari.webp',
                'gallery' => [
                    'packages/chitwan-wildlife-safari.webp',
                    'packages/gallery/chitwan-safari-2.webp',
                    'packages/gallery/chitwan-safari-3.webp',
                    'packages/gallery/chitwan-wildlife-safari-4.webp',
                ],
                'highlights' => [
                    'Jeep safari through Chitwan National Park\'s grasslands',
                    'Canoe ride along the Rapti River spotting gharial crocodiles and birdlife',
                    'Traditional Tharu stick dance performance on your one evening in the park',
                    'Guided walk through a local Tharu village',
                    'A tight, efficient itinerary built for travelers short on time',
                    'Chance encounters with one-horned rhinos, deer, and native birdlife',
                ],
                'itinerary' => [
                    [
                        'day' => 1,
                        'title' => 'Arrival, Jungle Safari & Tharu Culture',
                        'description' => 'Transfer to Chitwan and check in at your jungle lodge. Afternoon jeep safari through the national park, followed by a Tharu village walk and the evening stick dance performance.',
                    ],
                    [
                        'day' => 2,
                        'title' => 'Canoe Ride & Departure',
                        'description' => 'Early canoe ride along the Rapti River in search of rhinos and crocodiles, then breakfast and transfer out.',
                    ],
                ],
                'inclusions' => [
                    'Chitwan National Park entrance fees and permits',
                    'Jeep safari and canoe ride',
                    'Jungle lodge accommodation (1 night)',
                    'All meals during the safari',
                    'Naturalist guide and Tharu cultural show',
                ],
                'exclusions' => [
                    'Transport to/from Kathmandu or Pokhara',
                    'Alcoholic beverages',
                    'Personal expenses and tips',
                    'Travel insurance',
                ],
                'is_active' => true,
                'trip_grade' => 'Easy',
                'group_size_min' => 2,
                'group_size_max' => 12,
                'best_season' => 'Oct-Mar',
                'meals_note' => 'All meals included during the safari',
                'accommodation_note' => 'Jungle lodge (1 night)',
            ],
            [
                'title' => 'Everest View Trek',
                'slug' => 'everest-view-trek',
                'category' => 'Trekking',
                'duration' => '7-9 Days',
                'description' => 'A shorter Khumbu trek to the Everest View Hotel and Namche Bazaar — big Himalayan views and Sherpa culture, without needing Base Camp-level fitness or time.',
                'price' => '1450.00',
                'badge' => null,
                'image' => 'packages/everest-view-trek.webp',
                'gallery' => [
                    'packages/everest-view-trek.webp',
                    'packages/gallery/everest-view-trek-2.webp',
                    'packages/gallery/everest-view-trek-3.webp',
                    'packages/gallery/everest-base-camp-3.webp',
                ],
                'highlights' => [
                    'Everest, Lhotse, and Ama Dablam views from the Everest View Hotel',
                    'Namche Bazaar, the Khumbu\'s Sherpa trading hub',
                    'Tengboche Monastery, the spiritual center of the region',
                    'A gentler acclimatization pace than the full Base Camp trek',
                    'Sherpa village life in Khumjung and Khunde',
                    'A genuine taste of high-altitude trekking in under 10 days',
                ],
                'itinerary' => [
                    [
                        'day' => 1,
                        'title' => 'Fly to Lukla, Trek to Phakding',
                        'description' => 'Scenic mountain flight to Lukla, then an easy trek down to Phakding along the Dudh Koshi river.',
                    ],
                    [
                        'day' => 2,
                        'title' => 'Namche Bazaar',
                        'description' => 'Climb through pine forest to the Sherpa capital of the Khumbu, with your first close views of Everest en route.',
                    ],
                    [
                        'day' => 3,
                        'title' => 'Acclimatization Day',
                        'description' => 'Rest day in Namche with an optional hike up to the Everest View Hotel for panoramic mountain views.',
                    ],
                    [
                        'day' => 4,
                        'title' => 'Khumjung Village',
                        'description' => 'Visit the Sherpa villages of Khumjung and Khunde, including a local monastery and school.',
                    ],
                    [
                        'day' => 5,
                        'title' => 'Tengboche Monastery',
                        'description' => 'Trek to Tengboche for a close-up view of Ama Dablam and a visit to the Khumbu\'s most important monastery.',
                    ],
                    [
                        'day' => 6,
                        'title' => 'Return to Namche',
                        'description' => 'Descend back through rhododendron forest to Namche Bazaar.',
                    ],
                    [
                        'day' => 7,
                        'title' => 'Lukla',
                        'description' => 'Final descent to Lukla, with a farewell dinner in the evening.',
                    ],
                    [
                        'day' => 8,
                        'title' => 'Fly to Kathmandu & Departure',
                        'description' => 'Morning flight back to Kathmandu. A spare day is recommended given the unpredictability of mountain flights.',
                    ],
                ],
                'inclusions' => [
                    'Sagarmatha National Park permit and TIMS card',
                    'Domestic flights (Kathmandu-Lukla return)',
                    'Licensed guide and porter support',
                    'Teahouse accommodation',
                    'All meals during the trek',
                ],
                'exclusions' => [
                    'International flights',
                    'Nepal visa fees',
                    'Travel insurance',
                    'Hot showers and Wi-Fi at teahouses',
                    'Personal expenses and tips',
                ],
                'is_active' => true,
                'trip_grade' => 'Moderate',
                'group_size_min' => 2,
                'group_size_max' => 10,
                'best_season' => 'Mar-May, Sep-Nov',
                'meals_note' => 'All meals included on trek',
                'accommodation_note' => 'Teahouse lodges',
            ],
            [
                'title' => 'Nagarkot Sunrise & Changu Narayan Hike',
                'slug' => 'nagarkot-sunrise-changu-narayan-hike',
                'category' => 'Sightseeing',
                'duration' => '1 Day',
                'description' => 'A short escape from Kathmandu — sunrise over the Himalayan range from Nagarkot, followed by a gentle downhill hike to one of Nepal\'s oldest Hindu temples.',
                'price' => '70.00',
                'badge' => null,
                'image' => 'packages/nagarkot-sunrise-changu-narayan-hike.webp',
                'gallery' => [
                    'packages/nagarkot-sunrise-changu-narayan-hike.webp',
                    'packages/gallery/nagarkot-sunrise-changu-narayan-hike-2.webp',
                    'packages/gallery/nagarkot-sunrise-changu-narayan-hike-3.webp',
                ],
                'highlights' => [
                    'Sunrise over the Langtang and Everest ranges from Nagarkot',
                    'A gentle downhill hike through pine forest and terraced farmland',
                    'Changu Narayan, a UNESCO-listed temple older than Kathmandu itself',
                    'Intricately carved stone and metalwork dating back over 1,500 years',
                    'Village scenery largely untouched by the city below',
                    'A full day outside Kathmandu without an early multi-day commitment',
                ],
                'itinerary' => [
                    [
                        'day' => 1,
                        'title' => 'Nagarkot Sunrise & Changu Narayan Hike',
                        'description' => 'Pre-dawn drive to Nagarkot for sunrise over the Himalayan range, followed by breakfast. Hike downhill through forest and farmland to the ancient temple of Changu Narayan, then drive back to Kathmandu.',
                    ],
                ],
                'inclusions' => [
                    'Private vehicle from Kathmandu to Nagarkot and return from Changu Narayan',
                    'Licensed guide for the hike',
                    'Breakfast at Nagarkot',
                    'Changu Narayan entrance fee',
                ],
                'exclusions' => [
                    'Lunch and dinner',
                    'Personal expenses and tips',
                    'Travel insurance',
                ],
                'is_active' => true,
                'trip_grade' => 'Easy',
                'group_size_min' => 1,
                'group_size_max' => 10,
                'best_season' => 'Oct-Apr',
                'meals_note' => 'Breakfast at Nagarkot included',
                'accommodation_note' => 'Day tour - no overnight stay required',
            ],
            [
                'title' => 'Pokhara Adventure Add-ons',
                'slug' => 'pokhara-adventure-add-ons',
                'category' => 'Adventure',
                'duration' => 'Half-Day',
                'description' => 'Standalone adrenaline add-ons for your Pokhara stay — paragliding over Phewa Lake, ziplining down Sarangkot, or an ultralight flight past the Annapurna range. Book any combination alongside our Pokhara Valley Getaway.',
                'price' => '120.00',
                'badge' => null,
                'image' => 'packages/pokhara-adventure-add-ons.webp',
                'gallery' => [
                    'packages/pokhara-adventure-add-ons.webp',
                    'packages/gallery/pokhara-adventure-add-ons-2.webp',
                ],
                'highlights' => [
                    'Tandem paragliding over Phewa Lake with a certified pilot',
                    'One of Asia\'s longest ziplines, descending from Sarangkot',
                    'Ultralight flights past the Annapurna and Machapuchare skyline',
                    'No prior experience required for any activity',
                    'Flexible booking — pick one activity or combine several',
                    'Best paired with our Pokhara Valley Getaway package',
                ],
                'itinerary' => [
                    [
                        'day' => 1,
                        'title' => 'Choose Your Activity',
                        'description' => 'Select one or more activities — tandem paragliding, zipline, or ultralight flight — scheduled around your existing Pokhara stay, weather permitting.',
                    ],
                ],
                'inclusions' => [
                    'Certified pilot/instructor and full safety equipment',
                    'Hotel pickup and drop-off for the chosen activity',
                    'Activity-specific permits and insurance where required',
                ],
                'exclusions' => [
                    'Photo/video packages (available at an extra cost on-site)',
                    'Accommodation and meals (see Pokhara Valley Getaway)',
                    'Personal travel insurance',
                ],
                'is_active' => true,
                'trip_grade' => 'Easy (no experience required)',
                'group_size_min' => 1,
                'group_size_max' => 8,
                'best_season' => 'Sep-May, weather-dependent',
                'meals_note' => 'Not applicable',
                'accommodation_note' => 'Not applicable - activity add-on, not a standalone stay',
            ],
            [
                'title' => 'Kathmandu Food & Culture Walk',
                'slug' => 'kathmandu-food-culture-walk',
                'category' => 'Food & Culture',
                'duration' => 'Half-Day',
                'description' => 'A half-day food-first wander through Kathmandu\'s old town — street snacks, a family-run eatery, and the stories behind Newari cuisine, distinct from our temple-focused city tours.',
                'price' => '60.00',
                'badge' => null,
                'image' => 'packages/kathmandu-food-culture-walk.webp',
                'gallery' => [
                    'packages/kathmandu-food-culture-walk.webp',
                    'packages/gallery/kathmandu-food-culture-walk-2.webp',
                    'packages/gallery/kathmandu-food-culture-walk-3.webp',
                ],
                'highlights' => [
                    'Street-food stops through Ason and Indra Chowk\'s old bazaars',
                    'A sit-down Newari thali at a family-run eatery',
                    'Tasting momos, chatamari, and traditional yogurt from a working dairy',
                    'Behind-the-scenes look at a local spice and tea shop',
                    'Stories behind Newari food culture from a local food guide',
                    'A walking-paced route distinct from our temple-circuit tours',
                ],
                'itinerary' => [
                    [
                        'day' => 1,
                        'title' => 'Old Town Food Walk',
                        'description' => 'Meet in Kathmandu\'s old town for a walking route through Ason and Indra Chowk, stopping for street snacks, a spice shop visit, and a sit-down Newari thali at a family-run eatery.',
                    ],
                ],
                'inclusions' => [
                    'Local food guide',
                    'All tastings and one sit-down meal',
                    'Bottled water',
                ],
                'exclusions' => [
                    'Hotel pickup/drop-off (meeting point provided)',
                    'Alcoholic beverages',
                    'Personal expenses and tips',
                ],
                'is_active' => true,
                'trip_grade' => 'Easy',
                'group_size_min' => 1,
                'group_size_max' => 8,
                'best_season' => 'Year-round',
                'meals_note' => 'All tastings and one sit-down meal included',
                'accommodation_note' => 'Day tour - no overnight stay required',
            ],
        ];

        foreach ($packages as $data) {
            Package::updateOrCreate(['slug' => $data['slug']], $data);
        }
    }
}
